### ISSUE TITLE
JSON tricks cannot dump nan and infinity

### ISSUE THREAD

**Issue by liuzhe-lz** [mverleg/pyjson_tricks#63]
Although they are not included in JSON standard, it's sometimes useful to dump these values.
And they are supported in official Python library.

```python
>>> import math
>>> import json
>>> import json_tricks
>>> test_obj = {'nan': math.nan, 'inf': math.inf, 'neg_inf': -math.inf}
>>> json.dumps(test_obj)
'{"nan": NaN, "inf": Infinity, "neg_inf": -Infinity}'
>>> json_tricks.dumps(test_obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/json_tricks/nonp.py", line 98, in dumps
    txt = cls(sort_keys=sort_keys, obj_encoders=encoders, allow_nan=allow_nan,
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
>>> json.loads('{"nan": NaN, "inf": Infinity, "neg_inf": -Infinity}')
{'nan': nan, 'inf': inf, 'neg_inf': -inf}
>>> json_tricks.loads('{"nan": NaN, "inf": Infinity, "neg_inf": -Infinity}')
OrderedDict([('nan', nan), ('inf', inf), ('neg_inf', -inf)])
```

**Comment by liuzhe-lz** [comment]
Sorry, I didn't notice there is an `allow_nan` parameter.
Maybe you can mention it in README? I think I'm not the only one who ignore documentation for a library with really simple APIs...

**Comment by mverleg** [comment]
Glad you found it! I'm never really sure which parts of the API I should and shouldn't add to the README, I think everything is too much...
